<Project>
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>MoreUpgradedRewardsPreviews</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="0Harmony" Version="2.0.4" />
  </ItemGroup>
</Project>
