<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>MoreUpgradedCardPreviews</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
